### ISSUE TITLE
Problems using example code

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/documentation#12] opened 2019-01-10 13:59 UTC
There are several places where readers are provided with examples of code that they supposedly could cut and subsequently paste  in their own files. Examples are the `myModel.adl` in [Test to see if you can build your first prototype](https://ampersandtarski.gitbook.io/documentation/installing-ampersand/installing-the-tools-manually#test-to-see-if-you-can-build-your-first-prototype), or code snippets that can be found in the documentation of the ExecEngine, e.g. in [Example - Transitive Closure](https://ampersandtarski.gitbook.io/documentation/architecture-of-an-ampersand-application/extensions/the-execengine#example-transitiveclosure).

In courses that I recently gave, people that tried to do that complained that the stuff they paste in their editors contain weird characters, represented e.g. as `A,E^` (or something like that). In other editors, these characters do not show but do lead to compiler (parse) errors.

How can this be fixed? Is this something of the documentation, or is this something that the &-parser must deal with?

**Comment by WolframKahl** [comment] 2019-01-11 01:03
To some degree this is an education problem: In myu opinion, nobody
should expect that copy&paste from PDF to any kind of formal language
actually works in general.

**Comment by hanjoosten** [comment] 2019-01-11 06:38
I totally agree with @WolframKahl . It is also possible that the codepage setting of the editor isn't correctly set. The editor used should handle text in a proper way: Unicode characters encode with UTF8 is what we recomend. Just don't use any localized codepage settings or whatever crappy encodings were used in the former century. If you don't fully understand what I am talking about, [this article](https://www.joelonsoftware.com/2003/10/08/the-absolute-minimum-every-software-developer-absolutely-positively-must-know-about-unicode-and-character-sets-no-excuses/) is a must read.

**Comment by hanjoosten** [comment] 2019-01-11 06:40
I close this issue now, assuming above tips will do. Feel free to reopen, but then please leave a pointer to the specific piece in the documentation that is giving problems.

**Comment by RieksJ** [comment] 2019-01-11 20:06
@hanjoosten do you suggest that if you copy the example into your vscode editor you do not have this problem?

**Comment by hanjoosten** [comment] 2019-01-11 23:10
I have done some investigation. I can reproduce the issue. Unfortunately there is no simple solution we can do for ourselves. The problem is caused by the transformation from our markdown sourcefiles to the generated documentation. That is done using Gitbook. 
I have informed support of Gitbook about this bug. As soon as there is any progress on their side, I will update this issue.

**Comment by hanjoosten** [comment] 2019-01-11 23:11
As a workaround people should delete the invisible character at each seemingly empty line in the script, after copying it in their favorite editor.

**Comment by hanjoosten** [comment] 2019-01-21 11:38
I recieved a reply from the people of Gitbook. They have solved the issue. I have tested it and it works. From now on, the code snippets in our documentation can be copied and used as is.

**Closed as completed by hanjoosten** 2019-01-21 11:38 UTC
Labels: help wanted, question
